### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by rgieseke** [iiasa/ipcc_sr15_scenario_analysis#10]
Hi,

thanks for publishing these resources and for the open issue tracking, that should be super helpful!

I have a question on the scenario DB license:

> The scenario data is licensed under a derivative of the Creative Commons CC-BY 4.0 License. If appropriate reference is made to the data source, it is permitted to use the data for scientific research and science communication. However, redistribution of substantial portions of the data is restricted.

When I first skimmed the release info i thought this was actually released under a CC-BY license - the CC-BY license text can be re-used but I guess in order to avoid such confusion it is not allowed to use the name "Creative Commons" with modified licenses as I understand the conditions on https://creativecommons.org/licenses/by/4.0/legalcode
(Of course, I am not a lawyer ...)

> Except for the limited purpose of indicating that material is shared under a Creative Commons public license or as otherwise permitted by the Creative Commons policies published at creativecommons.org/policies, Creative Commons does not authorize the use of the trademark “Creative Commons” or any other trademark or logo of Creative Commons without its prior written consent including, without limitation, in connection with any unauthorized modifications to any of its public licenses or any other arrangements, understandings, or agreements concerning use of licensed material. For the avoidance of doubt, this paragraph does not form part of the public licenses.

Personally, I would of course prefer if the data were released under an established Open Data license, as creating new licenses and including vague terms like "substantial" often causes problems. (But that's probably an entirely different discussion.)

In any case, I think it would be better not to mention Creative Commons if it's not a Creative Commons license.

**Comment by danielhuppmann** [comment]
Thanks @rgieseke for raising this issue. There were two opposing requirements when drafting that page: on the one hand, not giving the impression that the data is released under a CC license; on the other hand, following scientific standards of clearly indicating where the material originates (and highlighting the differences between the original and the adapted text). In my (limited) understanding, the sentence *This public license is adapted from the Creative Commons Attribution 4.0 International Public License...* does not constitute a "use of their trademark".

Personally, I would find it weird if we did not indicate that the material is adapted from CC-BY, and not mentioning it at all would be an even greater risk that users mistakenly assume that it is CC-BY.

Would you think that adding a sentence clarifying that this license is not endorsed by *Creative Commons* would be an improvement?

**Comment by rgieseke** [comment]
Good points, coming from a science perspective, not mentioning also feels odd. For my "use case" of just quickly skimming a Readme spotting a familiar license name, thus knowing roughly what to expect, another sentence wouldn't make a difference.

I think the sentence in the Readme of this Repo (without the full description of differences as on the Scenario DB website) could easily be misunderstood:

> The scenario data is licensed under a derivative of the Creative Commons CC-BY 4.0 License. 

Most people are probably aware that there are different variants, SA, NC so one could think of these.
Maybe removing the sentence would be better.

From a user's perspective the "Creative Commons" linkage doesn't help me, because the license used here introduces new legal terms that are not easily understood or widely used.

**Comment by danielhuppmann** [comment]
Following some additional off-line conversations, all reference to Creative Commons will be removed as part of release 1.1 except for the "source" reference in the legal text.
