### ISSUE TITLE
SSP Scenarios - Missing climate variables

### ISSUE THREAD

**Issue by patrickrorourke** [iiasa/ipcc_sr15_scenario_analysis#14]
The SSP runs are reported as not having climate variables in the database, which creates problems when filtering and sorting by temperature. 

Since the SSP runs were designed to be linked to MAGICC, it would be helpful for the data users if MAGICC results were not only printed in diagnostics, but also reprinted in the regular climate variables (such as temperature).

**Comment by danielhuppmann** [comment]
Thanks @patrickrorourke for raising this issue. You are correct insofar as the current nomenclature is misleading.

There are two sets of variables in the dataset:
 - `Temperature|*`, `Concentration|*` and `Forcing|*` are the categories for variables reported by the modeling team for a particular scenario. These are not included in the IAMC 1.5°C Scenario data for the SSPs and other multi-model projects.  
 - `AR5 Climate Diagnostics|Temperature|*`, `AR5 Climate Diagnostics|Concentration|*` and `AR5 Climate Diagnostics|Forcing|*` are the variables for the climate impact assessment using probabilistic MAGICC (with the same configuration and emissions harmonization as used in AR5) and FAIR. This assessment was done centrally using the same methodology for all scenarios, and this data is available for all scenarios in the ensemble (which extended for the entire century and provided all required emissions species).

All assessments and categorization in the SR15 were done according to the second set of variables to ensure a consistent climate diagnostics setup. The first set of variables, where submitted by the teams, are only included for reference and completeness (e.g., to show where scenarios are published as 2°C-scenarios by the teams but are categorized differently in the SR15).

For IPCC AR6, my colleague @byersiiasa will lead the development of an extended variable template for the scenario compilation process. It's good to put that on the radar now to make sure that there is a more intuitive nomenclature for the next scenario compilation cycle.

**Comment by danielhuppmann** [comment]
Closing as this is misleading nomenclature, but not an error that will be adressed in the published scenario ensemble. Please re-open this issue if the explanation above is not adequate.
