### ISSUE TITLE
Cross-reference the github repository in the notebooks

### ISSUE THREAD

**Issue by nworbmot** [iiasa/ipcc_sr15_scenario_analysis#16]
When users land at:

https://data.ene.iiasa.ac.at/sr15_scenario_analysis/assessment.html

It's not obvious that there is also an accompanying github repository, so link the github repository from the notebooks / documentation.

**Comment by danielhuppmann** [comment]
Thanks @nworbmot for this suggestion! Will put this on my to-do list for later this week.

**Comment by danielhuppmann** [comment]
Thanks @nworbmot again for this suggestion, hope that this will make even more users download the notebooks and start playing around with them...

Finally done, all notebooks rerun with the latest release of `pyam` ([r0.2.0](https://pyam-iamc.readthedocs.io/en/v0.2.0/)), and created a new release of this repository ([v1.1.1_formatting](https://github.com/iiasa/ipcc_sr15_scenario_analysis/tree/v1.1.1_formatting)), implementing some minor formatting updates and reducing warnings when running with the latest `pyam` version.
