### ISSUE TITLE
Regional prices are incorrect

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ipcc_sr15_scenario_analysis#19]
During the compilation of the IAMC 1.5°C Data, we mistakenly applied a summation to all variables when aggregating model-native regions to the R5-regions. Instead, we should have used averages weighted by the respective quantities (carbon emissions, etc.).

As the SR15 assessment is only concerned with global assessments, this error does not affect any findings in the published report.

**Comment by danielhuppmann** [comment]
We have tried to fix this issue ex-post and update the scenario data, but this is beyond the scope of resources currently available. We will therefore remove all regional price data in the next release to avoid misleading analysis based on this data.

**Comment by nicobauer** [comment]
Hi Daniel,

hmm... it is however, very important to know the regional carbon prices to know what drives the transition in the various regions.

As long as the carbon prices are unifrom across regions, there is no problem. E.g. this is what we asked the teams to implement in EMF33.

But there might be other cases. I can understand, if you do the deletion for energy and food prices, but carbon prices is a bad example.

BEst
Nico

**Comment by danielhuppmann** [comment]
I fully understand your concern about removing potentially correct data, @nicobauer. However, reaching out to all teams and projects asking for whether the data is correct is not feasible given current resources, vacation plans at the contributing research groups, and the timeline for the forthcoming release to coincide with the IPCC SRCCL.
