### ISSUE TITLE
Scenario data used by stylised climate models

### ISSUE THREAD

**Issue by znicholls** [iiasa/ipcc_sr15_scenario_analysis#20]
Would it be possible to include the scenario data used by the stylised climate models as part of the SR1.5 climate assessment process as part of the next data release? This would be very helpful for many researchers and ensure that assumptions required to go from native model data to scenarios which can be used by stylised climate models are consistent and publicly available.

**Comment by danielhuppmann** [comment]
Thanks for this suggestion @znicholls - we will include this data in the next release.

**Comment by danielhuppmann** [comment]
@znicholls, I looked at the data you sent bilaterally in preparation for release 2.0 (following to the release of the IPCC SRCCL), and it seems to me that most it is actually already available - just in different units or naming conventions (carbon vs. carbon dioxide, Gt vs Mt, SOx vs. Sulfur, etc.). After conversion, I could not identify any significant data difference.

So simply adding this information risks confusion of non-expert users. Therefore, I would prefer to not include duplicate data entries in the data - instead, we could make the MAGICC input file in the native MAGICC convention available as a separate file in the 'Downloads' section of the Scenario Explorer.

@znicholls @chrisroadmap @rgieseke @svenwillner @gidden, any comments?

**Comment by znicholls** [comment]
Ok great. 

> So simply adding this information risks confusion of non-expert users

I agree let's not do that if it's already there. Can you talk me through how to get hold of it? At the moment there's a couple of problems.

1. If I go into the scenario explorer, some variables are greyed out (e.g. "Emissions|PFC|C2F6")

<img width="1413" alt="Screen Shot 2019-08-08 at 10 02 34 pm" src="https://user-images.githubusercontent.com/23625371/62701703-50e2a680-ba28-11e9-89e5-1d8eb1d76ba1.png">

2. The data on the database doesn't seem to be harmonised see e.g. CO2 emissions from MESSAGE-GLOBIOM 1.0 and AIM/CGE 2.0 for the ADVANCE_2020_1.5C-2100 scenario (while the data I sent is harmonised perfectly). 

<img width="1136" alt="Screen Shot 2019-08-08 at 10 04 44 pm" src="https://user-images.githubusercontent.com/23625371/62701840-956e4200-ba28-11e9-8af7-e9d417320056.png">

**Comment by danielhuppmann** [comment]
The timeseries variables `Emissions|*` are the data as submitted by modelling teams. If the specific data is greyed out, no data is available for the chosen models/scenarios in the previous tab.

The timeseries variables `Diagnostics|MAGICC6|Harmonized Input|Emissions|*` are the data after harmonisation and filling from background scenarios.

See [this workspace](https://data.ene.iiasa.ac.at/iamc-1.5c-explorer//#/workspaces/share/ea01cf0c-fc72-45c5-9e67-3e380608e5d5) for an illustration.

**Comment by znicholls** [comment]
> The timeseries variables `Diagnostics|MAGICC6|Harmonized Input|Emissions|*` are the data after harmonisation and filling from background scenarios

Ahah beauty thanks! All good from my end then

**Comment by znicholls** [comment]
> All good from my end then

Almost... Is there a reason the following scenarios have a different harmonisation to all the other scenarios (in 2010) in the workspace you shared? 

MESSAGE-GLOBIOM 1.0-EMF33_1.5C_cost100
MESSAGE-GLOBIOM 1.0-EMF33_1.5C_full
MESSAGE-GLOBIOM 1.0-EMF33_Baseline
MESSAGE-GLOBIOM 1.0-EMF33_Med2C_cost100
MESSAGE-GLOBIOM 1.0-EMF33_Med2C_full
MESSAGE-GLOBIOM 1.0-EMF33_Med2C_limbio
MESSAGE-GLOBIOM 1.0-EMF33_Med2C_nobeccs
MESSAGE-GLOBIOM 1.0-EMF33_Med2C_nofuel
MESSAGE-GLOBIOM 1.0-EMF33_Med2C_none
MESSAGE-GLOBIOM 1.0-EMF33_WB2C_cost100
MESSAGE-GLOBIOM 1.0-EMF33_WB2C_full
MESSAGE-GLOBIOM 1.0-EMF33_WB2C_limbio
MESSAGE-GLOBIOM 1.0-EMF33_WB2C_nofuel
MESSAGE-GLOBIOM 1.0-EMF33_tax_hi_full
MESSAGE-GLOBIOM 1.0-EMF33_tax_hi_none
MESSAGE-GLOBIOM 1.0-EMF33_tax_lo_full
MESSAGE-GLOBIOM 1.0-EMF33_tax_lo_none
MESSAGEix-GLOBIOM 1.0-CD-LINKS_INDCi
MESSAGEix-GLOBIOM 1.0-CD-LINKS_NPi
MESSAGEix-GLOBIOM 1.0-CD-LINKS_NPi2020_1000
MESSAGEix-GLOBIOM 1.0-CD-LINKS_NPi2020_1600
MESSAGEix-GLOBIOM 1.0-CD-LINKS_NPi2020_400
MESSAGEix-GLOBIOM 1.0-CD-LINKS_NoPolicy

<img width="699" alt="Screen Shot 2019-08-11 at 9 59 27 pm" src="https://user-images.githubusercontent.com/23625371/62833549-fa71a400-bc83-11e9-873c-94c8b05eb0d6.png">

In the data I sent through they've been adjusted so they do have the same harmonisation as all the other scenarios. I tried to work out how this was done but the two obvious choices didn't work (it's neither a constant scaling factor nor a constant offset...)

**Comment by znicholls** [comment]
@danielhuppmann any thoughts on this one if you have a minute?

**Comment by chrisroadmap** [comment]
I have also run into this issue, today in fact. Perhaps the harmonized emissions for these scenarios didn't get picked up in v2.0 - related to #1 possibly?

**Comment by danielhuppmann** [comment]
> I have also run into this issue, today in fact. Perhaps the harmonized emissions for these scenarios didn't get picked up in v2.0 - related to #1 possibly?

Unfortunately not related to #1 or release 2.0 (which didn't change any of these data points). I'll investigate.

**Comment by znicholls** [comment]
@danielhuppmann just a quick ping here to see if anything has come of your investigations, could be helpful learning for other work which is ongoing.

**Comment by znicholls** [comment]
@danielhuppmann was there ever an update on this (fine if not, we can implement a custom solution on our side)?

**Comment by danielhuppmann** [comment]
I didn't have a chance to do another release of the IAMC 1.5°C Scenario Ensemble and, to be honest, unless any critical inconsistencies are discovered, I won't be able to spend time on it in the coming months.

**Comment by znicholls** [comment]
Ok will close now then
