### ISSUE TITLE
API change

### ISSUE THREAD

**Issue by znicholls** [iiasa/ipcc_sr15_scenario_analysis#28]
@danielhuppmann has the API changed? Why do you get `meta` and `subannual` columns now when you download SR1.5 data via pyam?

**Comment by danielhuppmann** [comment]
@zikolach, can you please comment?

**Comment by zikolach** [comment]
Most probably this is related to the fact that back end for SR1.5 explorer was updated last week. If that's an issue we should add tests and (if not done) document API response.

**Comment by znicholls** [comment]
From a user perspective avoiding these sorts of surprises would be good I think

**Comment by danielhuppmann** [comment]
closing this issues as it is not related to the IPCC SR15 assessment notebooks directly - instead, I opened an issue in the `pyam`  repository (see reference above)
