### ISSUE TITLE
release 2.0 notebooks still load release 1.1 data by default

### ISSUE THREAD

**Issue by volker-krey** [iiasa/ipcc_sr15_scenario_analysis#30]
Several notebooks (I specifically checked sr15_2.3.3_short-lived_climate_forcers.ipynb and sr15_2.3.3_global_emissions_statistics.ipynb) by default still load release 1.1 data via the following command:
`sr1p5 = pyam.IamDataFrame(data='../data/iamc15_scenario_data_world_r1.1.xlsx')`
It would be useful to adjust this to loading release 2.0 data by default.

Also, in the introduction it is mentioned that the metadata file needs to be generated via the sr15_2.0_categories_indicators.ipynb notebook, but it seems metadata is readily available for download from the SR1.5 Scenario Explorer ([https://data.ene.iiasa.ac.at/iamc-1.5c-explorer]) which simplifies the process for the user and could be mentioned as an alternative.

**Comment by danielhuppmann** [comment]
Thank you @volker-krey for these suggestions to improve the user experience and reduce the scope for confusion!
