### ISSUE TITLE
'Price|Agriculture|***|Index' indexed to incorrect year in 'AIM' scenarios

### ISSUE THREAD

**Issue by kvcalvin** [iiasa/ipcc_sr15_scenario_analysis#7]
The units on Price|Agriculture|Non-Energy Crops and Livestock|Index and Price|Agriculture|Non-Energy Crops|Index say "Index (2010 = 1)", but the AIM data appear to be indexed to 2005.

**Comment by danielhuppmann** [comment]
@sfujimori, can you please double-check?

**Comment by shinichirofujimoriKU** [comment]
You are right. The price indices are not indexed to 2010. I have consulted with Daniel and he indicated that he will fix this issue in the next release. Thanks Daniel!!

**Comment by danielhuppmann** [comment]
Thanks @kvcalvin for reporting this issue and thanks @shinichirofujimoriKU for confirming.

This will be fixed as part of release 1.1.
