### ISSUE TITLE
Blank values for cumulative BECCS metadata

### ISSUE THREAD

**Issue by kellytrout** [iiasa/ipcc_sr15_scenario_analysis#9]
The metadata excel file (and related filters in the Scenarios Explorer) are not fully set up to filter for scenarios with zero BECCS. For example, the MESSAGEix-GLOBIOM 1.0 | LowEnergyDemand scenario implicitly has 0 cumulative BECCS (due to having 0 CCS). However, the spreadsheet is missing a value in the BECCS column. There are several dozen other scenarios that have a blank in either the cumulative CCS or cumulative BECCS metatdata columns, or both. It is not clear to me, given the existing metadata notes, how to filter and categorize these scenarios when querying data based on the CCS and BECCS metadata filters.

**Comment by danielhuppmann** [comment]
Thanks @kellytrout for identifying this issue. I'll look into it and keep you posted.

The implicit zero-value for cumulative BECCS in the `MESSAGEix-GLOBIOM 1.0 | LowEnergyDemand` scenario has been added for now in the online *IAMC 1.5°C Scenario Explorer*. Notebooks and data will be updated soon.
